name: C CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ammaraskar/gcc-problem-matcher@master

    - name: make
      run: make

